project '/Users/James/Desktop/xcode10Projects/Bware_ios/Bware.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
target "Bware" do
	pod 'Alamofire', '< 5.4.3'
	pod 'Flurry-iOS-SDK/FlurrySDK'
	pod 'Charts'
    pod 'GoogleMaps'
    pod 'BFPaperButton'
    pod 'RealmSwift'
    pod 'GoogleAPIClientForREST/Drive'
    pod 'Google/SignIn'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
use_frameworks!
